#
device: 'cuda'

# data settings
num_class: 10
# train_batch_size: 30 
# test_batch_size: 100
# TODO:(1/3)
train_batch_size: 20
test_batch_size: 20

# FL settings
# num_clients: 100
# TODO(0/3)
num_clients: 500
degree_non_iid: 0.9 # non-iid
num_epoch: 2000
C: 0.02
lr_global: 1 
time_step: 10

epoch_local: 1
# optim_local: 'Adam'
# TODO: (2/3)
optim_local: 'SGD'
mom_local: 0.9
lr_local: 0.1

# model settings
name_model: 'resnet'

# attack settings
ratio_comp: 0
type_attack: 'scaling'
# type_attack: 'scaling'

# defence settings
type_defense: 'None'

# path_ckpt: '../FedAVG_resnet18_cifar10_non_iid.pth'
# exp_name: 'FedAVG_resnet18_cifar10_non_iid'
# TODO: (3/3)
path_ckpt: '../FedAVG_resnet18_cifar10_SGD_non_iid.pth'
exp_name: 'FedAVG_resnet18_SGD_cifar10_SGD_non_iid'

load_idx: False 
load_model: False 
load_accs: False